<div class="main_footer pc row">
	<ul>
		<li><a href="#">会社概要</a></li>
		<li><a href="#">プライバシーポリシー</a></li>
		<li><a href="#">特定商取引法に基づく表記</a></li>
	</ul>
	<p>Copyright &copy; Marusei All Rights Reserved.</p>
</div>

<div class="footer_sp sp">
	<figure>
		<img src="./common/images/logo_footer.png" alt="Logo">
	</figure>
	<div class="tel_sp">
		<p class="phone_sp"><a href="tel:0120371580">0120-37-1580</a>（フリーダイヤル ミナ イーゴハン）<br><span>受付時間:月〜金 8:30-17:00</span></p>
		<p class="fax_sp">お電話やFAXのご注文もお受けしております<br>FAX番号：<strong>048-969-0020</strong></p>
	</div>
	<ul class="nav_sp">
		<li><a href="#">会社概要</a></li>
		<li><a href="#">特定商取引法に基づく表記</a></li>
	</ul>
	<a class="top top_footer" id="top_footer">
		<img src="./common/images/top.png" alt="Top">
	</a>
	<p class="copyright"><img src="./common/images/copyright_sp.png" alt="Copyright &copy; Marusei All Rights Reserved."></p>
</div>
