<div class="header_left">
  <h1 class="header_logo">
    <a href="#"><img class="resimg" src="./common/images/logo_pc.png" alt="logo"></a>
  </h1>
  <nav id="nav" class="nav">
    <ul>
      <li>
        <a href="#">About</a>
      </li>
      <li class="sp">
        <a href="#">Information</a>
      </li>
      <li>
        <a href="#">Products</a>
      </li>
      <li>
        <a href="#">Contact</a>
      </li>
      <li class="sp">
        <a href="#">Privacy Policy</a>
      </li>
    </ul>
  </nav>
  <div class="cart">
    <a href="#">
      <figure>
        <img class="resimg" src="./common/images/cart_pc.png" alt="Cart">
        <figcaption>2</figcaption>
      </figure>
      <em><span>4,500</span>円以上<br>送料無料</em>
    </a>
  </div>
  <div class="nav_ham" id="nav_ham"><span></span></div>
</div>
<div class="header_right">
  <div class="tel_box">
		<p class="tel">
			<span><img src="./common/images/tel_pc.png" alt="Icon Tel"></span>
			<a class="phone" href="tel:0120371580"><small>フリーダイヤル　ミナ　イーゴハン</small>0120-37-1580</a>
		</p>
		<p class="time">受付:月〜金 8:30-17:00 </p>
	</div>
	<p class="fax">お電話やFAXのご注文も受付中！　FAX：0120-37-1580</p>
</div>