<div class="main_header row">
  <div class="header_logo">
    <h1 class="left"><a href="http://www.sixapart.jp/movabletype/" target="_blank"><img src="/common/images/logo_pc.png" alt="logo"></a></h1>
    <a class="right" href="http://www.movabletype.jp/index.html" target="_blank">
      <span><img src="/common/images/btn_new.png" alt="button top" class="btn-top"></span>
    </a>
  </div>
  <nav id="nav" class="nav">
    <ul>
      <li><a href="/">Movable Type 5 の新機能</a></li>
      <li><a href="#">ライセンスについて</a></li>
      <li><a href="#">お知らせ</a></li>
      <li><a href="#">導入事例</a></li>
      <li><a href="#">関連製品・ソリューション</a></li>
    </ul>
  </nav>
</div>