<aside class="aside">
  <nav class="aside_menu" id="aside_menu">
    <ul>
      <li class="active" data-num="0"><span>TOP</span></li>
      <li data-num="1"><span>MESSAGE</span></li>
      <li data-num="2"><span>MEMBER<br>#01</span></li>
      <li data-num="3"><span>MEMBER<br>#02</span></li>
      <li data-num="4"><span>MEMBER<br>#03</span></li>
      <li data-num="5"><span>MEMBER<br>#04</span></li>
    </ul>
  </nav>
  <div class="aside_social">
    <span class="btn_share" id="btn_share"></span>
    <ul class="lst_share" id="lst_share">
      <li><a href="#"><i class="ic ic_facebook"></i></a></li>
      <li><a href="#"><i class="ic ic_twitter"></i></a></li>
    </ul>
  </div>
</aside>