<div class="main_header flex">
  <h1 class="header_logo">
    <a href="#"><img class="resimg" src="/test007/common/images/logo_pc.png" alt="logo"></a>
  </h1>
  <div class="nav_ham" id="nav_ham"><span></span></div>
  <div class="menu flex" id="menu">
  	<nav id="nav" class="nav">
	    <ul>
	      <li>
	      	<a href="#info"><img class="resimg" src="/test007/common/images/menu01_pc.png" alt="INFORMATION"></a>
	      </li>
	      <li>
	      	<a href="#product"><img class="resimg" src="/test007/common/images/menu02_pc.png" alt="PRODUCT"></a>
	      </li>
	      <li>
	      	<a href="#company"><img class="resimg" src="/test007/common/images/menu03_pc.png" alt="COMPANY"></a>
	      </li>
	      <li>
	      	<a href="#"><img class="resimg" src="/test007/common/images/menu04_pc.png" alt="RECRUIT"></a>
	      </li>
	      <li>
	      	<a href="#map"><img class="resimg" src="/test007/common/images/menu05_pc.png" alt="CONTACT"></a>
	      </li>
	      <li>
	      	<a href="#store"><img class="resimg" src="/test007/common/images/menu06_pc.png" alt="WEB STORE"></a>
	      </li>
	    </ul>
	  </nav>
	  <ul class="social">
	    <li><a href="#"><img class="resimg" src="/test007/common/images/facebook_pc.png" alt="facebook"></a></li>
	    <li><a href="#"><img class="resimg" src="/test007/common/images/twitter_pc.png" alt="twitter"></a></li>
	    <li><a href="#"><img class="resimg" src="/test007/common/images/insta_pc.png" alt="instagram"></a></li>
	  </ul>
  </div>
</div>