<ul class="slider" id="slider">
	<li class="slider_item">
		<img class="resimg" src="/test007/images/slide01_pc.png" alt="slider">
	</li>
	<li class="slider_item">
		<img class="resimg" src="/test007/images/slide02_pc.png" alt="slider02">
	</li>
	<li class="slider_item">
		<img class="resimg" src="/test007/images/slide03_pc.png" alt="slider03">
	</li>
	<!-- <li class="slider_item">
		<img class="resimg" src="/test007/images/slide04_pc.png" alt="slider04">
	</li> -->
	<li class="slider_item">
		<img class="resimg" src="/test007/images/slide05_pc.png" alt="slider05">
	</li>
</ul>