<div class="top-footer">
  <div class="row">
    <h2 class="footer-title">Movable Type 関連情報</h2>
    <ul class="footer-widget flex">
      <li class="footer-widget-item flex-item">
        <a href="https://www.sixapart.jp/movabletype/" target="_blank"><span>Movable Type 5 - Six Apart</span></a>
        <p>Movable Typeの提供をおこなうブログ専業のメーカーシックス・アパートの公式ページです。</p>
      </li>
      <li class="footer-widget-item footer-widget-middle flex-item">
       <a href="https://www.sixapart.jp/solutions/mtrs.html" target="_blank"><span>Movable Type リモートサービス</span></a>
        <p>インストール環境の設定からMovable Typeのアップグレード・構築後のサイト稼動監視までをオンラインで幅広くサポートいたします。</p>
      </li>
      <li class="footer-widget-item flex-item">
        <a href="http://www.sixapart.jp/movabletype/news/" target="_blank"><span>Movable Type ニュース</span></a>
        <p>Movable Type の最新情報はこちら。</p>
      </li>
    </ul>
    <ul class="footer-widget flex">
      <li class="footer-widget-item flex-item">
        <a href="http://www.movabletype.jp/pertinent/books/" target="_blank"><span>関連書籍</span></a>
        <p>Movable Type のカスタマイズや、サイト構築のサンプルなどが掲載されたオススメ書籍を紹介。</p>
      </li>
      <li class="footer-widget-item footer-widget-middle flex-item">
       <a href="https://www.sixapart.jp/movabletype/keitai-pack/" target="_blank"><span>Movable Type 携帯Pack</span></a>
        <p>Movable Typeで構築したブログやウェブサイトを携帯電話で閲覧できるようにするためのプラグイン製品。</p>
      </li>
      <li class="footer-widget-item flex-item">
        <a href="https://www.sixapart.jp/seminar/" target="_blank"><span>セミナー</span></a>
        <p>Movable Type に関するイベント・セミナー開催の情報。</p>
      </li>
    </ul>
  </div>
</div>
<div class="bottom-footer">
  <div class="bottom-footer-inner row flex">
    <figure class="bf-left">
      <img src="common/images/six_apart_logo.png" alt="Six apart logo">
      <span>シックス・アパートは、<a href="http://www.sixapart.jp/movabletype/" target="_blank">Movable Type</a> と <a href="http://www.sixapart.jp/typepad/" target="_blank">TypePad</a> 、<a href="http://www.sixapart.jp/vox/" target="_blank">Vox</a> の提供をおこなうブログ専業のメーカーです。</span>
    </figure>
    <p class="bf-right">Copyright 2003-2010 Six Apart, Ltd. All rights reserved.</p>
  </div>
</div>